"""init

Revision ID: 4479c9c060cc
Revises: 
Create Date: 2026-04-04 16:09:39.881475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4479c9c060cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('command_type', sa.Enum('door_open', 'door_close', 'set_mode', 'set_auto', 'feed_now', name='commandtype', native_enum=False, length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительные параметры команды в JSON. Примеры: {"mode_name": "day_frost"}'),
    sa.Column('is_executed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('heater', sa.Boolean(), nullable=False),
    sa.Column('ventilation', sa.Boolean(), nullable=False),
    sa.Column('lighting', sa.Boolean(), nullable=False),
    sa.Column('door', sa.Enum('open', 'closed', 'moving_open', 'moving_closed', name='doorstatus', native_enum=False, length=20), server_default='closed', nullable=False),
    sa.Column('feeder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('alarm_temp_high', 'alarm_temp_low', 'alarm_humidity', 'mode_change', 'door_open', 'door_close', 'feed_triggered', 'device_online', 'device_offline', 'sensor_error', 'camera_offline', name='eventtype', native_enum=False, length=50), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, length=20), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_time', sa.Time(), nullable=False, comment='Время кормления в формате HH:MM:SS (UTC). ESP32 сравнивает с текущим временем NTP.'),
    sa.Column('duration_seconds', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds BETWEEN 1 AND 60', name='check_duration_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи. BIGSERIAL — для больших объёмов'),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True, comment='Температура воздуха в °C. Диапазон: -40.00 … +85.00. NULL если датчик DHT22 вернул ошибку.'),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True, comment='Относительная влажность в %. Диапазон: 0.00 … 100.00. NULL если датчик DHT22 вернул ошибку.'),
    sa.Column('light_level', sa.Integer(), nullable=True, comment='Освещённость в люксах. Диапазон: 0 … 65535. NULL если датчик BH1750 вернул ошибку.'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Метка времени записи в UTC. DEFAULT NOW() — проставляется сервером при получении данных.'),
    sa.CheckConstraint('humidity >= 0 AND humidity <= 100', name='check_humidity_range'),
    sa.CheckConstraint('temperature >= -40 AND temperature <= 85', name='check_temp_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_readings_recorded_at', 'sensor_readings', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('system_modes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode_name', sa.Enum('day_moderate', 'day_frost', 'night_cold', 'overheat', 'manual', name='fsmmode', native_enum=False, length=50), nullable=False),
    sa.Column('is_auto', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Enum('system', 'user', name='changesource', native_enum=False, length=50), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), server_default='1', autoincrement=False, nullable=False),
    sa.Column('t_comfort_min', sa.Numeric(precision=5, scale=2), server_default='18.0', nullable=False, comment='Нижняя граница комфортной температуры.'),
    sa.Column('t_comfort_max', sa.Numeric(precision=5, scale=2), server_default='24.0', nullable=False, comment='Верхняя граница комфортной температуры.'),
    sa.Column('t_low_on', sa.Numeric(precision=5, scale=2), server_default='10.0', nullable=False, comment='Порог входа в дневной морозный режим.'),
    sa.Column('t_low_off', sa.Numeric(precision=5, scale=2), server_default='12.0', nullable=False, comment='Порог выхода из морозного режима (гистерезис).'),
    sa.Column('t_high_on', sa.Numeric(precision=5, scale=2), server_default='30.0', nullable=False, comment='Порог входа в режим перегрева.'),
    sa.Column('t_high_off', sa.Numeric(precision=5, scale=2), server_default='28.0', nullable=False, comment='Порог выхода из режима перегрева (гистерезис).'),
    sa.Column('t_critical_low', sa.Numeric(precision=5, scale=2), server_default='3.0', nullable=False, comment='Критически низкая температура. Аварийный обогрев принудительно включается даже в ручном режиме.'),
    sa.Column('t_critical_high', sa.Numeric(precision=5, scale=2), server_default='35.0', nullable=False, comment='Критически высокая температура. Аварийное охлаждение принудительно включается даже в ручном режиме.'),
    sa.Column('h_normal_max', sa.Numeric(precision=5, scale=2), server_default='70.0', nullable=False, comment='Порог включения вентиляции по влажности.'),
    sa.Column('h_normal_min', sa.Numeric(precision=5, scale=2), server_default='60.0', nullable=False, comment='Порог выключения вентиляции по влажности (гистерезис).'),
    sa.Column('h_critical', sa.Numeric(precision=5, scale=2), server_default='85.0', nullable=False, comment='Критическая влажность — аварийная принудительная вентиляция, push-уведомление severity=critical.'),
    sa.Column('lux_day_on', sa.Integer(), server_default='200', nullable=False, comment='Порог определения дневного времени суток.'),
    sa.Column('lux_day_off', sa.Integer(), server_default='150', nullable=False, comment='Порог определения ночного времени (гистерезис).'),
    sa.Column('lux_light_on', sa.Integer(), server_default='300', nullable=False, comment='Порог включения искусственного освещения.'),
    sa.Column('lux_light_off', sa.Integer(), server_default='350', nullable=False, comment='Порог выключения освещения (гистерезис).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='check_only_one_row'),
    sa.CheckConstraint('lux_day_on > lux_day_off', name='check_lux_day_hysteresis'),
    sa.CheckConstraint('t_high_on > t_high_off', name='check_t_high_hysteresis'),
    sa.CheckConstraint('t_low_off > t_low_on', name='check_t_low_hysteresis'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notif_alarm_temp_high', sa.Boolean(), server_default='true', nullable=False, comment='Получать push при высокой/критической температуре'),
    sa.Column('notif_alarm_temp_low', sa.Boolean(), server_default='true', nullable=False, comment='Получать push при низкой/критической температуре'),
    sa.Column('notif_alarm_humidity', sa.Boolean(), server_default='true', nullable=False, comment='Получать push при высокой/критической влажности'),
    sa.Column('notif_door_state', sa.Boolean(), server_default='true', nullable=False, comment='Получать push при изменении состояния двери'),
    sa.Column('notif_device_offline', sa.Boolean(), server_default='true', nullable=False, comment='Получать push когда ESP32 перестаёт'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(first_name) >= 2', name='check_first_name_len'),
    sa.CheckConstraint('char_length(last_name) >= 2', name='check_last_name_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='pushplatform', native_enum=False, length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='idx_push_tokens_token')
    )
    op.create_index('idx_push_tokens_user_id', 'push_tokens', ['user_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_push_tokens_user_id', table_name='push_tokens', postgresql_where=sa.text('is_active = true'))
    op.drop_table('push_tokens')
    op.drop_table('users')
    op.drop_table('thresholds')
    op.drop_table('system_modes')
    op.drop_index('idx_sensor_readings_recorded_at', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('feed_schedule')
    op.drop_table('event_log')
    op.drop_table('device_states')
    op.drop_table('device_commands')
    # ### end Alembic commands ###
