"""add api_key to user

Revision ID: 6c41f7389ec8
Revises: d0b110a72b2c
Create Date: 2026-04-07 13:35:37.461523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.config.security import generate_api_key

# revision identifiers, used by Alembic.
revision: str = '6c41f7389ec8'
down_revision: Union[str, Sequence[str], None] = 'd0b110a72b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_users_api_key', 'users', ['api_key'])
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)

    users = session.execute(sa.text("SELECT id FROM users")).fetchall()

    for user in users:
        session.execute(
            sa.text("UPDATE users SET api_key = :api_key WHERE id = :id"),
            {"api_key": generate_api_key(), "id": user.id}
        )
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
